general.import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[env]
TERM = "xterm-256color"

[window]
position = { x = 661, y = 630 }
dimensions = { columns = 175, lines = 60 }
padding = { x = 8, y = 8}
dynamic_padding = true
# decorations = "Buttonless"
# Unhighlight for rounded borders (macos only)
decorations = "None"
opacity = 0.75
blur = false # Set to true for transparent background
option_as_alt = "Both"

[scrolling]
multiplier = 4 

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular"}

[selection]
save_to_clipboard = true 

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "tmux attach || tmux"
  ]

[keyboard]
bindings = [
    { key = "F10", action = "ToggleFullscreen" },
    { key = "F1", action = "ToggleViMode" },
    ]
