import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
position = { x = 661, y = 630 }
dimensions = { columns = 175, lines = 60 }
padding = { x = 8, y = 8}
# dynamic_padding = true
# decorations = "Buttonless"
# Unhighlight for rounded borders (macos only)
decorations = "None"
opacity = 0.75
blur = true
option_as_alt = "Both"

[scrolling]
multiplier = 2 

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"
  

[selection]
save_to_clipboard = true 


[mouse]
hide_when_typing = true

[shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "tmux attach || tmux"
  ]

