live_config_reload = true

[colors.bright]
black = "0x585B70"
blue = "0x89B4FA"
cyan = "0x94E2D5"
green = "0xA6E3A1"
magenta = "0xF5C2E7"
red = "0xF38BA8"
white = "0xA6ADC8"
yellow = "0xF9E2AF"

[colors.cursor]
cursor = "0xCDD6F4"
text = "0x1E1E2E"

[colors.normal]
black = "0x45475A"
blue = "0x89B4FA"
cyan = "0x94E2D5"
green = "0xA6E3A1"
magenta = "0xF5C2E7"
red = "0xF38BA8"
white = "0xBAC2DE"
yellow = "0xF9E2AF"

[colors.primary]
background = "0x1E1E2E"
foreground = "0xCDD6F4"

[cursor]
blink_interval = 750
style = "Beam"
thickness = 0.125

[font]
size = 8.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 5000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = true

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 10
y = 10
